<?php

/**
 * Implements hook_init()
 * Use it for following in this module:
 * 1. To insert taxonomy for food menu
 */

function firangiland_custom_init(){

  // $row = 1;
  // if (($handle = fopen(drupal_get_path('module', 'firangiland_custom') . "/includes/food_menu.csv", "r")) !== FALSE) {

  //     while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
  //         $num = count($data);
  //         $row++;
  //           for ($c=0; $c < $num; $c++) {
  //               // echo $data[$c] . "<br />\n";

  //               taxonomy_term_save((object) array(
  //                 'name' =>  $data[$c],
  //                 'vid' => '3',
  //               ));
  //             }
  //         }
  //     fclose($handle);
  // }
  // below code is to delete all the terms 
  // $vocabulary = taxonomy_vocabulary_machine_name_load('main_menu');
  //   foreach (taxonomy_get_tree($vocabulary->vid) as $term) {
  //     taxonomy_term_delete($term->tid);
  //   }

}



/**
 * Implements hook_form_alter().
 *
 * Hide average fivestar field from review edit/create form.
 */
function firangiland_custom_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'review_for_restaurant_node_form') {
    // Hide average field, this field is calculated upon node_presave.
    $form['field_overall_average']['#access'] = FALSE;
  }


}


/**
 * Implements hook_node_presave().
 *
 * Calculates average vote rating.
 */
function firangiland_custom_node_presave($node) {

  if ($node->type == 'review_for_restaurant') {
    // Get values from 3 axis.
    $vote_food     = entity_metadata_wrapper('node', $node)->field_food->value();
    $vote_ambience      = entity_metadata_wrapper('node', $node)->field_ambience->value();

    // Calculate and set average axe.
    $votes_average      = ($vote_food + $vote_ambience) / 2;
    // @info: Can't use entity_metadata_wrapper, because '->set' not supported on this field.
    //entity_metadata_wrapper('node', $node)->field_overall_average->set($votes_average);
    $node->field_overall_average['und'][0]['rating'] = $votes_average;  

    
  }
}



